baseURL = "https://snowynight.site/"
locale = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "shadow 的编程网"
theme = "blowfish"
timeZone = "Asia/Shanghai"
enableRobotsTXT = true
summaryLength = 36

[pagination]
  pagerSize = 8

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]